### ISSUE TITLE
US05 - Ativar crédito especial

### ISSUE THREAD

**Issue by mlfaa** [fga-eps-mds/2019.2-Grupo2#23]
## História de Usuário

Eu, como usuário, desejo ativar ou desativar o crédito especial da minha conta, para que seja possível gerenciar meus gastos mensais.

## Tasks
- [x] Design da tela de ativar oferta de crédito
- [x] Design da escolha do tipo de crédito 
- [x] Design da tela de ativação de crédito

## Critérios de Aceitação

- [x] O design da tela de ativar oferta de crédito deve estar igual ao do vídeo
- [x] O design da escolha do tipo de crédito deve estar igual ao do vídeo
- [x] O designda tela de ativação de crédito deve estar igual ao do vídeo

## ScreenShot 
![](https://uploaddeimagens.com.br/images/002/327/087/full/Captura_de_tela_de_2019-09-06_22-27-59.png?1567822098)

![](https://uploaddeimagens.com.br/images/002/327/083/full/Captura_de_tela_de_2019-09-06_22-28-32.png?1567821956)

![](https://uploaddeimagens.com.br/images/002/327/085/full/Captura_de_tela_de_2019-09-06_22-29-00.png?1567822037)

Link do vídeo : https://www.youtube.com/watch?v=T6JfLJ1zaXA&feature=youtu.be
